esphome:
  platform: esp32
  name: century-vs-pump-controller
  board: pico32
  on_boot:
    then:
      light.turn_on:
        id: id_light_1
        blue: 1.0
        brightness: 0.3
        green: 1.0
        red: 1.0
wifi:
  ap:
    password: !secret ap_PWD
    ssid: century-vs-pump-controller
  password: !secret wifi_PWD
  ssid: !secret wifi_SSID
captive_portal:
logger:
api:
  password: !secret api_PWD
ota:
  password: !secret ota_PWD
time:
  - platform: homeassistant
    id: homeassistant_time
external_components:
  # Location of CenturyVSPump component implementation
  - source:
      type: git
      url: https://github.com/gazoodle/CenturyVSPump
      ref: main
binary_sensor:
  - platform: gpio
    name: Pool Pump Controller button
    pin:
      inverted: True
      number: GPIO39
button:
  - platform: template
    name: Pool Pump Controller Demand 600RPM
    id: id_button_7
    on_press:
      then:
        - number.set:
            id: id_number_rpm
            value: 600
  - platform: template
    name: Pool Pump Controller Demand 2600RPM
    id: id_button_6
    on_press:
      then:
        - number.set:
            id: id_number_rpm
            value: 2600
  - platform: template
    name: Pool Pump Controller Demand 3450RPM
    id: id_button_8
    on_press:
      then:
        - number.set:
            id: id_number_rpm
            value: 3450
centuryvspump:
light:
  - platform: neopixelbus
    name: Pool Pump Controller LED
    id: id_light_1
    num_leds: 1
    pin: GPIO27
    variant: SK6812
modbus:
  id: id_modbus_3
number:
  - platform: centuryvspump
    name: Pool Pump Controller Demand
    id: id_number_rpm
sensor:
  - platform: wifi_signal
    name: Pool Pump Controller Wifi Signal
    update_interval: 60min
  - platform: centuryvspump
    name: "Motor Operating Mode"
    type: custom
    address: 2
    page: 0  
  - platform: centuryvspump
    name: "Motor Demand"
    type: custom
    address: 3
    page: 0  
    unit_of_measurement: "rpm"
    scale: 4
  - platform: centuryvspump
    name: "Motor Torque"
    type: custom
    address: 4
    page: 0  
    unit_of_measurement: "ft-lb"
  - platform: centuryvspump
    name: "Input Power"
    type: custom
    address: 5
    page: 0
    unit_of_measurement: "W"  
  - platform: centuryvspump
    name: "DC Bus Voltage"
    type: custom
    address: 6
    page: 0  
    scale: 64
  - platform: centuryvspump
    name: "Ambient Temperature"
    type: custom
    address: 7
    page: 0  
    scale: 128
    unit_of_measurement: "°C"
  - platform: centuryvspump
    name: "Status"
    type: custom
    address: 8
    page: 0  
  - platform: centuryvspump
    name: "Previous Fault"
    type: custom
    address: 9
    page: 0  
  - platform: centuryvspump
    name: "Output Power"
    type: custom
    address: 0xa
    page: 0  
    unit_of_measurement: "W"  
  - platform: centuryvspump
    name: "SVRS Bypass Status"
    type: custom
    address: 0xb
    page: 0  
  - platform: centuryvspump
    name: "Current Faults"
    type: custom
    address: 0xc
    page: 0  
  - platform: centuryvspump
    name: "Motor Line Voltage"
    type: custom
    address: 0xd
    page: 0
    unit_of_measurement: "V"
    scale: 10
  - platform: centuryvspump
    name: "Ramp Status"
    type: custom
    address: 0xe
    page: 0
  - platform: centuryvspump
    name: "Total Faults"
    type: custom
    address: 0xf
    page: 0  
  - platform: centuryvspump
    name: "Prime Status"
    type: custom
    address: 0x10
    page: 0  
  - platform: centuryvspump
    name: "Motor Input Power"
    type: custom
    address: 0x11
    page: 0  
  - platform: centuryvspump
    name: "IGBT Temperature"
    type: custom
    address: 0x12
    page: 0
    scale: 128
    unit_of_measurement: "°C"
  - platform: centuryvspump
    name: "PCB Temperature"
    type: custom
    address: 0x13
    page: 0
    scale: 128
    unit_of_measurement: "°C"
  - platform: centuryvspump
    name: "Prime Detection Timer"
    type: custom
    address: 2
    page: 1  
  - platform: centuryvspump
    name: "Prime Verify Timer"
    type: custom
    address: 3
    page: 1
  - platform: centuryvspump
    name: "SVRS Functionality"
    type: custom
    address: 3
    page: 1
  - platform: centuryvspump
    name: "Entrapment Detection"
    type: custom
    address: 5
    page: 1
  - platform: centuryvspump
    name: "SVRS Bypass Timer"
    type: custom
    address: 6
    page: 1
  - platform: centuryvspump
    name: "Serial Timeout Counter"
    type: custom
    address: 7
    page: 1
  - platform: centuryvspump
    name: "Total Run Time Low"
    type: custom
    address: 8
    page: 1
    unit_of_measurement: Hours
  - platform: centuryvspump
    name: "Total Run Time High"
    type: custom
    address: 9
    page: 1
    unit_of_measurement: Hours
  - platform: centuryvspump
    name: "Total Lifetime Low"
    type: custom
    address: 0xa
    page: 1
    unit_of_measurement: Hours
  - platform: centuryvspump
    name: "Total Lifetime High"
    type: custom
    address: 0xb
    page: 1
    unit_of_measurement: Hours
  - platform: centuryvspump
    name: "Total Session Timer Low"
    type: custom
    address: 0xd
    page: 1
    unit_of_measurement: Hours
  - platform: centuryvspump
    name: "Total Session Timer High"
    type: custom
    address: 0xd
    page: 1
    unit_of_measurement: Hours    
  - platform: centuryvspump
    name: "Fault Timer Low"
    type: custom
    address: 0xe
    page: 1
  - platform: centuryvspump
    name: "Fault Timer High"
    type: custom
    address: 0xf
    page: 1
switch:
  - platform: centuryvspump
    name: Pool Pump Controller Run
    id: id_switch_4
uart:
  id: id_uart_2
  baud_rate: 9600
  debug:
  rx_pin: GPIO22
  tx_pin: GPIO19
web_server:
  local: True
  port: 80
